# Generated by Django 4.0.3 on 2022-03-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='email',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='basics',
            name='phone',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='basics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
