# Generated by Django 4.0.3 on 2022-04-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_basics_email_basics_phone_alter_basics_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basics',
            new_name='Contact',
        ),
    ]
