# Generated by Django 4.0.3 on 2022-04-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_rename_basics_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['firstname']},
        ),
    ]
