# Generated by Django 4.0.3 on 2022-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
