# Generated by Django 4.0.3 on 2022-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=1024)),
                ('note', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'ordering': ['site'],
            },
        ),
    ]
